import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";

const inter = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-3xl mx-auto p-4">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
